### ISSUE TITLE
There is no information about vector data extensions 

### ISSUE THREAD

**Issue by pawelgajewski-gis-support** [gis-support/cloud#2]
1. What behavior were you expecting?

Information about vector data extensions (possible choice of extension or list of supported formats).

2. What actually happened?

There is no information in upload modal.

3. How can I reproduce it?

Dashboard > Add new layer

4. What was your environment like?

Chrome 79

**Comment by gis-support** [comment]
please add select input under the coordinate system with keys: ESRI Shapefile, GeoJSON, GML.
For ESRI Shapefile, dropzone need to accept extensions: * .cpg, * .dbf, * .prj, * .qpj, * .shp, * .shx
for GeoJSON: * .geojson
for GML: * .gml
